# Generated by Django 4.1.4 on 2022-12-27 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraField',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ImageField(null=True, upload_to='Creatorprofile')),
                ('address', models.TextField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
